services:
  database:
    image: postgres:17.5-alpine3.22
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: synchronus_db
    volumes:
      - synchronus_db_data:/var/lib/postgresql/data

volumes:
  synchronus_db_data:
